version: '3'
services:
  php:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - './src:/var/www/html'
  
  nginx:
    image: nginx:latest
    ports:
      - 80:80
    volumes:
      - './src:/var/www/html'
      - './src/server-conf:/etc/nginx/conf.d'
      - './src/index.php:/usr/share/nginx/html/index.php'
  
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    platform: linux/amd64
    restart: always
    ports:
      - 8077:80
    environment:
      # - PMA_ARBITRARY=1
      - PMA_HOST=db
    depends_on:
      - db

  db:
    image: mysql:8
    ports:
      - '5506:3306'
    restart: unless-stopped
    environment:
      - MYSQL_USER=root
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_PASSWORD=root
      - MYSQL_DATABASE=shop-db
    volumes:
      - './src/mysql:/var/lib/mysql'