version: '3'
services:
  php:
    # image: php:8.1-fpm
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - './src:/var/www/html'
  
  nginx:
    image: nginx:latest
    ports:
      - 80:80
    volumes:
      - './src:/var/www/html'
      - './src/server-conf:/etc/nginx/conf.d'
  
  mysql:
    image: mysql:8
    environment:
      - MYSQL_ROOT_PASSWORD=root
    volumes:
      - './src/mysql:/var/lib/mysql'