version: '3'
services:
  php:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - './src:/var/www/html'

      # - './src/pages:/var/www/html/pages'
      # - './src/php:/var/www/html/php'
  
  nginx:
    image: nginx:latest
    ports:
      - 80:80
    volumes:
      - './src:/var/www/html'
      - './src/server-conf:/etc/nginx/conf.d'
      # - './src/index.php:/usr/share/nginx/html/index.php'
      # - './src/pages/index.php:/usr/share/nginx/html/index.php'

      # - './src/js:/var/www/html/js'
      # - './src/css:/var/www/html/css'
      # - './src/assets:/var/www/html/assets'


  
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    platform: linux/amd64
    restart: always
    ports:
      - 8077:80
    environment:
      # - PMA_ARBITRARY=1
      - PMA_HOST=db
    depends_on:
      - db

  db:
    image: mysql:8
    ports:
      - '5506:3306'
    restart: unless-stopped
    environment:
      # - MYSQL_USER=root
      # - MYSQL_ROOT_PASSWORD=root
      # - MYSQL_PASSWORD=root
      # - MYSQL_DATABASE=shop

      - MYSQL_USER=egor
      - MYSQL_ROOT_PASSWORD=egor
      - MYSQL_PASSWORD=egor
      - MYSQL_DATABASE=shop
    volumes:
      - './src/mysql:/var/lib/mysql'